FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
COPY columns.json .
COPY artifacts/ artifacts/

EXPOSE 8501

CMD ["streamlit", "run", "src/app_streamlit.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
